### ISSUE TITLE
Windows specific issue: `unlink': Permission denied @ apply2files - D:/a/_temp/open-uri20240109-8000-qkpcnk (Errno::EACCES)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-index#4]
<details>
  <summary>Full stack trace</summary>

  ```
  D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/nodes/scalar.rb:65: warning: Exception   in finalizer #<Tempfile::Remover:0x000001ffe62f8270 @pid=8000, @tmpfile=#<File:D:/a/_temp/open-uri20240109-8000-qkpcnk (closed)>>
  C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `unlink': Permission denied @ apply2files - D:/a/_temp/  open-uri20240109-8000-qkpcnk (Errno::EACCES)
  	from C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `call'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/nodes/scalar.rb:65:in   `initialize'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/tree_builder.rb:97:in `new'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/tree_builder.rb:97:in `scalar'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/parser.rb:62:in `_native_parse'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/parser.rb:62:in `parse'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych.rb:455:in `parse_stream'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych.rb:399:in `parse'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych.rb:323:in `safe_load'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-index-0.2.8/lib/relaton/index/  file_io.rb:134:in `fetch_and_save'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-index-0.2.8/lib/relaton/index/  file_io.rb:40:in `read'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-index-0.2.8/lib/relaton/index/type.rb:21:in   `index'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-index-0.2.8/lib/relaton/index/type.rb:63:in   `search'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  hit_collection.rb:46:in `fetch_from_gh'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  hit_collection.rb:18:in `initialize'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  iec_bibliography.rb:19:in `new'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  iec_bibliography.rb:19:in `search'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  iec_bibliography.rb:129:in `search_filter'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  iec_bibliography.rb:250:in `iecbib_get'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  iec_bibliography.rb:35:in `get'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iec-1.18.0/lib/relaton_iec/  processor.rb:18:in `get'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-1.18.0/lib/relaton/db.rb:192:in `fetch_doc'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-1.18.0/lib/relaton/db.rb:483:in `net_retry'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-1.18.0/lib/relaton/db.rb:447:in `fetch_entry'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-1.18.0/lib/relaton/db.rb:435:in   `new_bib_entry'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-1.18.0/lib/relaton/db.rb:407:in   `check_bibliocache'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-1.18.0/lib/relaton/db.rb:69:in `fetch'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iev-1.1.6/lib/relaton_iev.rb:45:in `block in   refs_iev2iec60050part'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iev-1.1.6/lib/relaton_iev.rb:44:in `each'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iev-1.1.6/lib/relaton_iev.rb:44:in   `refs_iev2iec60050part'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/relaton-iev-1.1.6/lib/relaton_iev.rb:76:in   `iev_cleanup'
  	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/cleanup.rb:63:in `cleanup'
  	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:207:in `makexml'
  	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:152:in `document1'
  	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/base.rb:141:in `document'
  	from D:/a/metanorma-standoc/metanorma-standoc/lib/metanorma/standoc/utils.rb:13:in `convert'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/  document.rb:956:in `convert'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/asciidoctor-2.0.20/lib/asciidoctor/convert.rb:120:in   `convert'
  	from D:/a/metanorma-standoc/metanorma-standoc/spec/metanorma/cleanup_ref_spec.rb:396:in `block (3 levels) in <top (required)>'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr/util/  variable_args_block_caller.rb:9:in `call_block'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/vcr-6.1.0/lib/vcr.rb:194:in `use_cassette'
  	from D:/a/metanorma-standoc/metanorma-standoc/spec/metanorma/cleanup_ref_spec.rb:238:in `block (2 levels) in <top (required)>'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in   `instance_exec'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in   `block in run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in   `block in with_around_and_singleton_context_hooks'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in   `block in with_around_example_hooks'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in   `block in run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in   `block in run_around_example_hooks_for'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in   `call'
  	from D:/a/metanorma-standoc/metanorma-standoc/spec/spec_helper.rb:40:in `block (2 levels) in <top (required)>'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in   `instance_exec'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in   `instance_exec'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in   `execute_with'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in   `block (2 levels) in run_around_example_hooks_for'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in   `call'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in   `run_around_example_hooks_for'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in   `run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in   `with_around_example_hooks'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in   `with_around_and_singleton_context_hooks'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in   `run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/  example_group.rb:646:in `block in run_examples'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/  example_group.rb:642:in `map'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/  example_group.rb:642:in `run_examples'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/  example_group.rb:607:in `run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in   `block (3 levels) in run_specs'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in   `map'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in   `block (2 levels) in run_specs'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/  configuration.rb:2070:in `with_suite_hooks'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in   `block in run_specs'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in   `report'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in   `run_specs'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in   `run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in   `run'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in   `invoke'
  	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/rspec-core-3.12.2/exe/rspec:4:in `<main>'
  ```
</details>

https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20294257836#step:6:64

Happens for Ruby 3.1+

Possible inspiration to fix: https://github.com/metanorma/metanorma/pull/307

**Comment by andrew2net** [comment]
@CAMOBAP as I see in the log the error is caused when any attempt to remove temp file is occurred. In the case the gem `psych` creates temp file and tries to remove it. It's not the relaton-index problem, and it can't be solved in the relaton-index.

Other gems also try to remove temp files and cause the error. For example:
- Nokogiri https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20294257836#step:6:181
- Parslet https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20294257836#step:6:462

**Comment by CAMOBAP** [comment]
@andrew2net to be on the same page this temp file isn't created buy [`URI.open`](https://ruby-doc.org/stdlib-2.7.2/libdoc/open-uri/rdoc/OpenURI.html), but `psych`module?

In the Nokogiri and Parslet no `psych` was involved, so I had an assumption that temp file was passed to them (the same as to `psych` released/removed before processing is done. can it be the case?

**Comment by andrew2net** [comment]
@CAMOBAP I'm digging into the problem. The code that raises the error is in `Tempfile::Remover#call` method:
```ruby
  class Remover # :nodoc:
    def initialize(tmpfile)
      @pid = Process.pid
      @tmpfile = tmpfile
    end

    def call(*args)
      return if @pid != Process.pid

      $stderr.puts "removing #{@tmpfile.path}..." if $DEBUG

      @tmpfile.close
      begin
        File.unlink(@tmpfile.path) # !!The Errno::EACCES is raised here!!
      rescue Errno::ENOENT
      end

      $stderr.puts "done" if $DEBUG
    end
  end
```
The `Tempfile::Remover` class is used as finalizer for garbage collector. From the `Tempfile` doc:

>   The underlying file is removed when the \Tempfile object dies
>   and is reclaimed by the garbage collector.

So the `Tempfile::Remover#call` method is called by Ruby garbage collector because in some dependency tempfile was created and wasn't deleted explicitly.

If we look at the `Tempfile#unlink` method:
```ruby
  def unlink
    return if @unlinked
    begin
      File.unlink(@tmpfile.path)
    rescue Errno::ENOENT
    rescue Errno::EACCES
      # may not be able to unlink on Windows; just ignore
      return
    end
    ObjectSpace.undefine_finalizer(self)
    @unlinked = true
  end
  alias delete unlink
```
we can se that the `Errno::EACCES` is ignored here. There is even a comment denoted that the error may occurs on Windows specifically. I don't know why the same approach isn't used in `Tempfile::Remover#call`. As a workaround we can monkey patch the `Tempfile::Remover#call` method. It's not a very good solution but I don't see any other way how to solve this problem.

**Comment by CAMOBAP** [comment]
Just to be on the same page who controls this `Tempfile` creation?

In the case of a similar issue with` metanorma` our code was responsible for `Tempfile` and by keeping explicit reference to it we were able to fix this issue

If it out of our control I propose to report some issue to third party gem and close this one

**Comment by andrew2net** [comment]
> @andrew2net to be on the same page this temp file isn't created buy [`URI.open`](https://ruby-doc.org/stdlib-2.7.2/libdoc/open-uri/rdoc/OpenURI.html), but `psych`module?

@CAMOBAP the temp file may be created by `URI.open`. I just saw `psych` in the backtrace and thought that it is involved:
```
C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `unlink': Permission denied @ apply2files - D:/a/_temp/open-uri20240109-8000-qkpcnk (Errno::EACCES)
	from C:/hostedtoolcache/windows/Ruby/3.2.2/x64/lib/ruby/3.2.0/tempfile.rb:279:in `call'
	from D:/a/metanorma-standoc/metanorma-standoc/vendor/bundle/ruby/3.2.0/gems/psych-5.1.2/lib/psych/nodes/scalar.rb:65:in `initialize'
```
I think it's highly likely that the temp file was created by `URI.open`. I'll try to remove the IO object that `URI.open` returns.

**Comment by andrew2net** [comment]
@CAMOBAP I've updated relaton-index. Now it removes the tempfile that open-uri creates. Please try relaton v0.2.10.

**Comment by CAMOBAP** [comment]
it looks like it still reproduces https://github.com/metanorma/metanorma-standoc/actions/runs/7458621234/job/20376510755

To me, it looks like an issue that `psych` trying access to tempfile that it deleted already, so probably the fix should be with "retaining" the Tempfile object lifetime

**Comment by andrew2net** [comment]
> To me, it looks like an issue that `psych` trying access to tempfile that it deleted already, so probably the fix should be with "retaining" the Tempfile object lifetime

I thought the same way a the beginning but it is not. The method that fails called by garbage collector. It runs in another thread and we see a mess of messages from different threads in the log. So the tempfile was unbounded from context just before `psych` started parsing. I found that zip gem creates tempfile object with the same file name but with different object_id. So I've updated the relaton-index to close and unlink the tempfile as well. Please try relaton-index v0.2.11

**Comment by andrew2net** [comment]
@CAMOBAP If it fails again, we can find all the open-uri usage and try to close tempfiles explicitly:
```ruby
resp = URI(url).open
# use the resp before close it
resp.close! if resp.is_a? Tempfile
```
I think it may help because all the problem tempfiles have open-uri string in their names `D:/a/_temp/open-uri20240111-7040-bg5f7o`
I can check all the relaton-* gems, but I don't know if metanorma uses open-uri or not.

**Comment by alemorozov** [comment]
@andrew2net @CAMOBAP I was working on metanorma/metanorma-standoc#855 and got up with the following solution:

```ruby
resp = StringIO.new(URI(url).read)
```

It avoids using a temporary file at all and specs have no warnings now:
https://github.com/metanorma/metanorma-standoc/pull/856/checks

If it's fine with the overall intention, I need approval to run CI in a PR:
https://github.com/relaton/relaton-index/pull/5

**Comment by andrew2net** [comment]
@alexeymorozov cool, I'll release the PR
